jwt:
  secret: sdfmnsdfw234f
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto1
    username: usuario
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG