jwt:
  secret: sdfmnsdfw234fufh83uh4f8u432hfu84n3fn38uf4n8u34nf8un3ufnejrnieGHTRH4535343434534543543DWerge34534gdfgdfg
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyectos
    username: usuario
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG